name: 'Deploy to Dev'
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    name: 'Deploy to Databricks Dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - run: databricks bundle deploy
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_DEV }}
          DATABRICKS_BUNDLE_ENV: dev
